module.exports = {
	compilationOptions: { preferredConfigPath: './tsconfig.json' },
	entries: [
		'index',
		'accordion-types',
		'alert-types',
		'avatar-types',
		'badge-types',
		'banner-types',
		'breadcrumb-types',
		'button-group-types',
		'button-types',
		'card-types',
		'command-types',
		'drop-types',
		'feedback-types',
		'font-types',
		'footer-types',
		'form-types',
		'grid-types',
		'head-types',
		'header-types',
		'hero-types',
		'html-types',
		'icon-types',
		'input-group-types',
		'link-types',
		'list-group-types',
		'loader-types',
		'menu-types',
		'modal-types',
		'navbar-types',
		'nav-types',
		'pagination-types',
		'prefooter-types',
		'progress-bar-types',
		'radio-types',
		'range-types',
		'route-types',
		'section-types',
		'slide-types',
		'spinner-types',
		'switch-types',
		'table-types',
		'tab-types',
		'tag-types',
		'toast-types',
		'tooltip-types',
	].map(fileName => ({
		filePath: `./src/${fileName}.tsx`,
		outFile: `./dist/${fileName}.d.ts`,
		noCheck: true,
	})),
};
