import * as types from '@playbooks/types';
export declare const Card: ({ name, tailwind, className, children, ...props }: types.CardProps) => import("react/jsx-runtime").JSX.Element;
export declare const CardHeader: ({ name, tailwind, className, children, ...props }: types.CardHeaderProps) => import("react/jsx-runtime").JSX.Element;
export declare const CardIcon: ({ name, type, icon, tailwind, className, ...props }: types.CardIconProps) => import("react/jsx-runtime").JSX.Element;
export declare const CardImg: ({ name, alt, tailwind, className, children, ...props }: types.CardImgProps) => import("react/jsx-runtime").JSX.Element;
export declare const CardBody: ({ name, tailwind, className, children, ...props }: types.CardBodyProps) => import("react/jsx-runtime").JSX.Element;
export declare const CardPretitle: ({ name, tailwind, className, children, ...props }: types.CardPretitleProps) => import("react/jsx-runtime").JSX.Element;
export declare const CardTitle: ({ name, size, tailwind, className, children, ...props }: types.CardTitleProps) => import("react/jsx-runtime").JSX.Element;
export declare const CardSubtitle: ({ name, tailwind, className, children, ...props }: types.CardSubtitleProps) => import("react/jsx-runtime").JSX.Element;
export declare const CardText: ({ name, tailwind, className, children, ...props }: types.CardTextProps) => import("react/jsx-runtime").JSX.Element;
export declare const CardFooter: ({ name, tailwind, className, children, ...props }: types.CardFooterProps) => import("react/jsx-runtime").JSX.Element;
export declare const CardActions: ({ name, tailwind, className, children, ...props }: types.CardActionsProps) => import("react/jsx-runtime").JSX.Element;
