import * as types from '@playbooks/types';
export declare const Drop: ({ ref, name, open, onClose, tailwind, className, children, ...props }: types.DropProps) => import("react/jsx-runtime").JSX.Element;
export declare const DropToggle: ({ name, alt, variant, nextIcon, onClick, tailwind, className, children, ...props }: types.DropToggleProps) => import("react/jsx-runtime").JSX.Element;
export declare const DropMenu: ({ ref, name, open, placement, options, tailwind, className, children, ...props }: types.DropMenuProps) => import("react/jsx-runtime").JSX.Element;
export declare const DropHeader: ({ name, tailwind, className, children, ...props }: types.DropHeaderProps) => import("react/jsx-runtime").JSX.Element;
export declare const DropTitle: ({ name, tailwind, className, children, ...props }: types.DropTitleProps) => import("react/jsx-runtime").JSX.Element;
export declare const DropSubtitle: ({ name, tailwind, className, children, ...props }: types.DropSubtitleProps) => import("react/jsx-runtime").JSX.Element;
export declare const DropList: ({ name, tailwind, className, children, ...props }: types.DropListProps) => import("react/jsx-runtime").JSX.Element;
export declare const DropItem: ({ name, tailwind, className, children, ...props }: types.DropItemProps) => import("react/jsx-runtime").JSX.Element;
export declare const DropBtn: ({ name, tailwind, className, children, ...props }: types.DropBtnProps) => import("react/jsx-runtime").JSX.Element;
export declare const DropLink: ({ name, tailwind, className, children, ...props }: types.DropLinkProps) => import("react/jsx-runtime").JSX.Element;
