import * as types from '@playbooks/types';
export declare const Form: ({ id, name, onSubmit, tailwind, className, children, ...props }: types.FormProps) => import("react/jsx-runtime").JSX.Element;
export declare const FormGroup: ({ name, tailwind, className, children, ...props }: types.FormGroupProps) => import("react/jsx-runtime").JSX.Element;
export declare const FormLabel: ({ id, name, htmlFor, onClick, tailwind, className, children, ...props }: types.FormLabelProps) => import("react/jsx-runtime").JSX.Element;
export declare const FormCheckbox: ({ id, name, checked, onChange, readOnly, tailwind, className, ...props }: types.FormCheckboxProps) => import("react/jsx-runtime").JSX.Element;
export declare const FormInput: ({ id, ref, name, type, size, value, variant, placeholder, onChange, onFocus, onBlur, onClick, readOnly, tailwind, className, ...props }: types.FormInputProps) => import("react/jsx-runtime").JSX.Element;
export declare const FormMaskInput: ({ id, name, size, mask, value, variant, placeholder, onChange, onBlur, readOnly, tailwind, className, ...props }: types.FormInputMaskProps) => import("react/jsx-runtime").JSX.Element;
export declare const FormCurrencyInput: ({ id, name, size, value, variant, prefix, placeholder, onChange, onBlur, readOnly, tailwind, className, ...props }: types.FormInputCurrencyProps) => import("react/jsx-runtime").JSX.Element;
export declare const FormDivInput: ({ id, name, size, value, variant, placeholder, onClick, tailwind, className, children, ...props }: types.FormInputProps) => import("react/jsx-runtime").JSX.Element;
export declare const FormFileInput: ({ id, name, value, placeholder, onChange, tailwind, className, ...props }: types.FormFileProps) => import("react/jsx-runtime").JSX.Element;
export declare const FormLocationInput: ({ id, name, size, value, variant, options, placeholder, googleMapsApiKey, onChange, onSelect, onBlur, readOnly, tailwind, className, ...props }: types.FormInputLocationProps) => import("react/jsx-runtime").JSX.Element;
export declare const FormSelect: ({ id, name, size, value, variant, options, placeholder, disabled, onChange, tailwind, className, ...props }: types.FormSelectProps) => import("react/jsx-runtime").JSX.Element;
export declare const FormText: ({ name, tailwind, className, children, ...props }: types.FormTextProps) => import("react/jsx-runtime").JSX.Element;
export declare const FormTextArea: ({ id, name, size, value, variant, rows, placeholder, onChange, readOnly, tailwind, className, ...props }: types.FormTextAreaProps) => import("react/jsx-runtime").JSX.Element;
