import * as types from '@playbooks/types';
export declare const Hero: ({ name, size, tailwind, className, children, ...props }: types.HeroProps) => import("react/jsx-runtime").JSX.Element;
export declare const HeroBg: ({ name, ref, tailwind, className, children, ...props }: types.HeroBgProps) => import("react/jsx-runtime").JSX.Element;
export declare const HeroImg: ({ name, alt, size, src, tailwind, className, ...props }: types.HeroImgProps) => import("react/jsx-runtime").JSX.Element;
export declare const HeroIcon: ({ name, size, icon, tailwind, className, ...props }: types.HeroIconProps) => import("react/jsx-runtime").JSX.Element;
export declare const HeroBody: ({ name, tailwind, className, children, ...props }: types.HeroBodyProps) => import("react/jsx-runtime").JSX.Element;
export declare const HeroPretitle: ({ name, tailwind, className, children, ...props }: types.HeroPretitleProps) => import("react/jsx-runtime").JSX.Element;
export declare const HeroTitle: ({ name, size, tailwind, className, children, ...props }: types.HeroTitleProps) => import("react/jsx-runtime").JSX.Element;
export declare const HeroSubtitle: ({ name, size, tailwind, className, children, ...props }: types.HeroSubtitleProps) => import("react/jsx-runtime").JSX.Element;
export declare const HeroText: ({ name, tailwind, className, children, ...props }: types.HeroTextProps) => import("react/jsx-runtime").JSX.Element;
export declare const HeroActions: ({ name, tailwind, className, children, ...props }: types.HeroActionsProps) => import("react/jsx-runtime").JSX.Element;
