module.exports = {
	compilationOptions: { preferredConfigPath: './tsconfig.json' },
	entries: [
		'index',
		'animation',
		'chart',
		'context',
		'currency-input',
		'date-picker',
		'date-range-picker',
		'drag-drop',
		'fade',
		'font-awesome',
		'google-autocomplete',
		'masked-input',
		'phone-input',
		'scrollspy',
		'skeleton',
		'star-rating',
		'waypoint',
	].map(fileName => ({
		filePath: `./src/${fileName}.tsx`,
		outFile: `./dist/${fileName}.d.ts`,
		noCheck: true,
	})),
};
