module.exports = {
	compilationOptions: { preferredConfigPath: './tsconfig.json' },
	entries: [
		'index',
		'accordions',
		'alerts',
		'avatars',
		'badges',
		'banners',
		'breadcrumbs',
		'button-groups',
		'buttons',
		'cards',
		'commands',
		'drops',
		'feedbacks',
		'fonts',
		'footers',
		'forms',
		'grid',
		'head',
		'headers',
		'heros',
		'html',
		'icons',
		'input-groups',
		'links',
		'list-groups',
		'loaders',
		'menus',
		'modals',
		'navbars',
		'navs',
		'paginations',
		'prefooters',
		'progress-bars',
		'radios',
		'ranges',
		'routes',
		'sections',
		'slides',
		'spinners',
		'switches',
		'tables',
		'tabs',
		'tags',
		'toasts',
		'tooltips',
	].map(fileName => ({
		filePath: `./src/${fileName}.tsx`,
		outFile: `./dist/${fileName}.d.ts`,
		noCheck: true,
	})),
};
